.gitignore
Gemfile
lib/puppet/provider/hocon_setting/ruby.rb
lib/puppet/util/config_saver.rb
spec/acceptance/conf_setting_spec.rb
spec/acceptance/nodesets/default.yml
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

Modify the puppetlabs-hocon module to use the new ConfigDocument
API rather than the Config API for value addition/file rendering.

(TK-191) Use ConfigDocument API

---

Gemfile
README.markdown
lib/puppet/provider/hocon_setting/ruby.rb
lib/puppet/type/hocon_setting.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

This PR adds support for Arrays, Hashes, and rendered text (the text of the value as it should appear in the configuration file) for the value parameter.
This PR is based on https://github.com/puppetlabs/puppetlabs-hocon/pull/7, so that should get merged before this is reviewed.
This PR will also require the changes in https://github.com/puppetlabs/ruby-hocon/pull/55 being released and the gemfile updated before it can be merged.

(TK-192) Support Arrays

---

README.markdown

Fix README examples to match what will be output by the actual
module.
@cprice404 Here are the fixes for those examples you pointed out

(MAINT) Fix README examples

---

lib/puppet/provider/hocon_setting/ruby.rb
lib/puppet/type/hocon_setting.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb
spec/unit/puppet/type/hocon_setting_spec.rb

Previously, the type would check the type of value being passed in the DSL
and would use that type when setting the value in the Hocon config file
(i.e. a string value would be a string in the config file, and an array
would be an array value). The problem is that versions of Puppet < 4.0.0
stringify all values passed in the DSL, so it was impossible to pass a true
numeric value via the DSL (since it would be stringified).
This commit updates the type validation to account for this and implements
a munge block to convert the value type to a numeric. A test for this case
has also been added.

Handle stringified numerics

---

Gemfile
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

Due to a bug in the hocon gem, the hocon module would previously
generate ugly single-line configuration when creating a config
from scratch. Update to hocon 0.9.2 to remove this behavior.

(MAINT) Update to hocon 0.9.2

---

README.markdown
lib/puppet/provider/hocon_setting/ruby.rb
lib/puppet/type/hocon_setting.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb
spec/unit/puppet/type/hocon_setting_spec.rb

This allows elements in arrays in hocon files to managed individually.

Add array_element

---

lib/puppet/provider/hocon_setting/ruby.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

This commit changes the behavior for applying an `array_element` when
the array does not exist in the target file yet from displaying an error
to creating the array and populating it with the element.

(HC-33) Support adding element when array does not exist yet

---

Gemfile
lib/puppet/provider/hocon_setting/ruby.rb
lib/puppet/type/hocon_setting.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

Previously, if a setting existed on disk as a scalar and the puppet resource changed the setting's type to array, the file would not be updated to reflect this explicit type.
In addition to the new unit test, I manually tested this and saw the fix working locally. I am unable to run the acceptance tests.
I've never touched types and providers before and have barely written ruby, so in many ways I feel like I was coding in the dark. Extra scrutiny on this PR would be great!

(HC-31) Handle type change from scalar -> array

---

lib/puppet/feature/hocon.rb
lib/puppet/provider/hocon_setting/ruby.rb

Previously, we guarded requiring the hocon gem based on the feature, but
we never re-evaluated the feature, so you couldn't use the hocon module
in the same run that the hocon gem was installed.
This commit moves the requiring logic into the feature definition, and
confines the provider based on the hocon feature.

(HC-46) Confine provider based on hocon feature

---

README.markdown
lib/puppet/type/hocon_setting.rb
spec/acceptance/conf_setting_spec.rb
spec/unit/puppet/type/hocon_setting_spec.rb

Make the path and setting parameters namevars, thus ensuring that
Puppet will give an error if two resources manage the same hocon
setting in the same file.
To implement this I ended up needing to make some changes to the API. This change should be compatible with all existing puppet code written using the `hocon_setting` type unless the user was explicitly setting `name`. 
When we release this change we should either release the module as 0.10.0 or 1.0.0.

(HC-30) Make path and setting namevars

---

Rakefile

Update the PuppetLint configuration to prevent failures in CI.
Eventually we'll need to add hocon to modulesync but in the mean
time this will prevent failures.

(maint) Update PuppetLint configuration

---

tests/hocon_setting.pp

Prior to this commit there was an indentation error in
hocon_settings.pp that was causing lint to issue a warning and thus
CI jobs to fail. Fix the indention in the file so that lint no
longer finds any issues to warn about.

(maint) Fix indentation error in test file

---

spec/unit/puppet/provider/conf_setting/ruby_spec.rb

Prior to this commit, some of the spec tests were failing on Ruby
2.2 and newer. This was due to the fact that the way variable names
are handled and scoped had changed, and we were unintentionally
overloading a variable name. In order to fix this issue, change
one of the variable names so they do not conflict.

(HC-91) Make tests compatible with newer ruby versions

---

spec/unit/puppet/provider/conf_setting/ruby_spec.rb

The 1.2.4 release of the hocon ruby gem made some small changes to
the output with regards to whitespace. Update the tests in the
module to reflect these changes.

(HC-98) Update specs to reflect new output format

---

.sync.yml
Gemfile

Since the hocon gem is only used in unit tests, move it to the
:development section in the Gemfile.

(maint) Move the hocon gem to development

---

spec/spec_helper_acceptance.rb

Prior to this commit, the test setup was using the same gem
provider for PE and FOSS and all versions. Correct this so that
it using the correct provider with certain versions of puppet and
PE.

(maint) Use correct providers to install gems

---

spec/spec_helper_acceptance.rb

Correct the conditional for determining which gem provider to use
so that it works with versions of PE older than 4.0.

(maint) Correct gem installation conditional

---

spec/spec_helper_acceptance.rb

The previous commit contained an error. Unwrap 'puppet_version' in
the first conditional statement, it should not be passed into
Gem::Version.new().to_s first.

(maint) Actually fix conditional statement

---

README.markdown

Fix markdown

---

.sync.yml

This module has been released to drop puppet 3 so we will no longer allow deprecated functions via unit testing.

(MODULES-4854) remove allow_deprecations

---

metadata.json

Adding Debian and Ubuntu supported versions to align with the following document: https://puppet.com/docs/pe/2017.3/installing/supported_operating_systems.html.

Updating supported OS for Ubuntu and Debian

---

lib/puppet/provider/hocon_setting/ruby.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

The ConfigDocument API that preserves comments and formatting in HOCON
files does not automatically resolve substitutions. This makes it
impossible to manipulate settings that involve substitutions. This
commit adds a `resolve` call to the config object that is parsed and
provided for manipulation.

(maint) Resolve config object before manipulating it

---

README.md
lib/puppet/type/hocon_setting.rb
spec/unit/puppet/provider/conf_setting/ruby_spec.rb

* Added a workaround for a bug in Puppet as demonstrated in HC-99
* Add key deletion example
* Update README.md with example of deleting a top-level key
* Add test as a verification example
HC-99 #close

[HC-99] Fix to replace an existing array with an empty array

---

metadata.json

Dropped support for:
* EL 6
* Debian 7, 8, and 9
* Ubuntu 14.04, and 16.04

(maint) drop unsupported operating systems

---

metadata.json

Adds support for:
* Debian 10, 11, and 12
* Ubuntu 20.04 and 22.04
* SLES 12

Update Debian, Ubuntu, and SLES support
